//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatisHareketler
    {
        public int SatisID { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Adet { get; set; }
        public decimal Fiyat { get; set; }
        public decimal ToplamTutar { get; set; }
        public int CariID { get; set; }
        public int PersonelID { get; set; }
        public int UrunID { get; set; }
    
        public virtual Cariler Cariler { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
